// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchTool_ServerSide.Data;

#nullable disable

namespace SearchTool_ServerSide.Migrations
{
    [DbContext(typeof(SearchToolDBContext))]
    [Migration("20250204212821_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchTool_ServerSide.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ACQ")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AWP")
                        .HasColumnType("numeric");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("DrugClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("NDC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rxcui")
                        .HasColumnType("integer");

                    b.Property<string>("Strength")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrugClassId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrugClasses");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugInsurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer");

                    b.Property<string>("NDCCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InsuranceId", "DrugId");

                    b.HasIndex("DrugId");

                    b.ToTable("DrugInsurances");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServerSide.Models.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcquisitionCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("DrugName")
                        .HasColumnType("text");

                    b.Property<string>("Insurance")
                        .HasColumnType("text");

                    b.Property<string>("NDCCode")
                        .HasColumnType("text");

                    b.Property<string>("Prescriber")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RxCui")
                        .HasColumnType("integer");

                    b.Property<string>("RxNumber")
                        .HasColumnType("text");

                    b.Property<string>("ScriptCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.Drug", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.DrugClass", "DrugClass")
                        .WithMany()
                        .HasForeignKey("DrugClassId");

                    b.Navigation("DrugClass");
                });

            modelBuilder.Entity("SearchTool_ServerSide.Models.DrugInsurance", b =>
                {
                    b.HasOne("SearchTool_ServerSide.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchTool_ServerSide.Models.Insurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Insurance");
                });
#pragma warning restore 612, 618
        }
    }
}
