name: Deploy to EC2

on:
  push:
    branches:
      - v6  # تنفيذ الـ CI/CD عند الـ push على فرع v6

jobs:
  deploy:
    runs-on: self-hosted  # تشغيل على السيرفر

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        run: |
          ssh -i "C:\Users\youss\Downloads\server\Hannalla_key.pem" ec2-user@ec2-13-60-77-166.eu-north-1.compute.amazonaws.com << 'EOF'
          
            echo "Pulling latest changes..."
            cd /home/ec2-user/app
            git reset --hard  # تأكد إنك على آخر نسخة من الكود
            git pull origin v6

            echo "Building .NET application..."
            dotnet publish -c Release -o published

            echo "Restarting service..."
            sudo systemctl restart kestrel-searchtool

            echo "Restarting Nginx..."
            sudo systemctl restart nginx

            echo "Deployment completed successfully!"
          EOF
